services:
  - type: web
    name: nexus-junction-backend
    env: python
    region: singapore # Change to your preferred region
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn main:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FRONTEND_ORIGIN
        value: https://nexus-junction-frontend.vercel.app
